input {
    kb_layout = latam
    kb_variant =
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0
    force_no_accel = 1
    numlock_by_default = true
}

device {
    name = 8bitdo-retro-87-keyboard-x-keyboard
    kb_layout = us
}

device {
    name = logitech-g815-rgb-mechanical-gaming-keyboard
    kb_layout = us
}

cursor {
    no_hardware_cursors = true
}
